name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Cache ♻
        uses: egordm/gha-yarn-node-cache@v1

      - name: Setup wasm-pack 📦✨
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install 🔧
        run: yarn install

      - name: Build 🏗️
        run: yarn build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
